### ISSUE TITLE
Consider moving code into Sequence as a constructor 

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#1]
https://github.com/rkaushik15/api-compliance-framework/blob/330c26a67b44f6265468f7979ec27f5876d1324b/src/main/java/org/ga4gh/RefgetUtilities/RefgetUtilities.java#L56

This is the only point where we create a Sequence object, that I've found. Consider moving the code into Sequence as a constructor with the parameters `new Sequence(jsonObject, sequence)`. It may be possible to build another constructor for `new Sequence(jsonObject)` which uses the sequence name to locate the sequence in question. Here are some examples:

```java 
    public Sequence(JSONObject json) throws IOException {
        this(json, (String)json.get("name")+".faa");
    }

    // Expected constructor to use (creates the object and populates sequence)
    public Sequence(JSONObject json, String sequenceName) throws IOException {
        this.name = (String) json.get("name");
        this.md5 = (String) json.get("md5");
        this.sha512 = (String) json.get("sha512");
        this.circular = (Boolean) json.get("circular");
        this.sequence = RefgetUtilities.readSequence(sequenceName);
    }
```

**Comment by rkaushik15** [comment]
Made the relevant changes.
