### ISSUE TITLE
Use booleans rather than numerics

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#10]
https://github.com/rkaushik15/api-compliance-framework/blob/5e23d75ebf2b3fd6561d0b9705212dbe51122f1e/resources/checksums.json#L6

Consider using a JSON boolean type e.g.

```json
"is_circular": false,
```

Or if it's a true value

```json
"is_circular": true,
```

And this will affect the Sequence object construction. https://github.com/rkaushik15/api-compliance-framework/blob/master/src/main/java/org/ga4gh/RefgetUtilities/Sequence.java#L45

**Comment by rkaushik15** [comment]
Fixed.
