### ISSUE TITLE
Could sequence become an immutable object

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#2]
https://github.com/rkaushik15/api-compliance-framework/blob/330c26a67b44f6265468f7979ec27f5876d1324b/src/main/java/org/ga4gh/RefgetUtilities/Sequence.java#L7

If there is no reason for modifying the object post construction, then consider making it immutable i.e. remove all setter methods from the object.

**Comment by rkaushik15** [comment]
Correct, right now there is no need to have mutable Sequence objects, will see if in future cases there is need. Removing Getters.
