### ISSUE TITLE
LogManager.getLogger can take a class as an argumnet

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#3]
https://github.com/rkaushik15/api-compliance-framework/blob/330c26a67b44f6265468f7979ec27f5876d1324b/src/main/java/org/ga4gh/RefgetUtilities/RefgetUtilities.java#L24

You can rewrite the Logger create statements as so. This could make the code slightly cleaner to read.

```java
private static Logger log = LogManager.getLogger(RequestsRestAssured.class);
```

**Comment by rkaushik15** [comment]
Done.
