### ISSUE TITLE
toString should be asString

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#4]
https://github.com/rkaushik15/api-compliance-framework/blob/330c26a67b44f6265468f7979ec27f5876d1324b/src/main/java/org/ga4gh/ComplianceFramework/ResponseProcessor.java#L26

The code here is incorrect. The correct method is `asString()`.

```java
String responseString =  response.getBody().asString();
```

**Comment by rkaushik15** [comment]
Fixed.
