### ISSUE TITLE
CAPITAL variables should be reserved for static constants and Java uses camel case normally

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#5]
https://github.com/rkaushik15/api-compliance-framework/blob/330c26a67b44f6265468f7979ec27f5876d1324b/src/main/java/org/ga4gh/ComplianceFramework/Server.java#L21

Anything written as `CAPITAL_SNAKE_CASE` is assumed to be a constant. Snake_case is not normally used. You should consider switching this code to use normal casing i.e.

```java
private String baseUrl;
private Map<String, Object> serverProperties;

public String getBaseUrl() {
    return baseUrl;
}
```

**Comment by rkaushik15** [comment]
Made the relevant changes. This inspired a nice reading of Java conventions, thanks :)
