### ISSUE TITLE
Do not swallow exceptions and consider smaller code

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#6]
https://github.com/rkaushik15/api-compliance-framework/blob/330c26a67b44f6265468f7979ec27f5876d1324b/src/main/java/org/ga4gh/ComplianceFramework/Utilities.java#L22

You shouldn't swallow exceptions. Add `IOException` to the throws statement. Also consider switching methods to simpler versions e.g. 

```java
Path path = Paths.get(Constants.RESOURCE_DIR + filename);
byte[] content = readAllBytes(path);
return new String(content, Constants.ENCODING_UTF8);
```

**Comment by rkaushik15** [comment]
I chose the longer method to parse the string line by line to deal with HUGE files. The readAllBytes() method loads the whole file in the memory in one go. Usually, this isn't an issue but it may cause problems with files in the ~100MB range even on systems with respectable memory capacities (8 GB), throwing an OutOfMemoryException. Reading in chunks would never have that issue. 
So, in our use case is it possible to encounter such files?
And should we keep this application anyway, to support systems with lower configurations?

**Comment by andrewyatz** [comment]
Can you confirm where you found the 100MB issue? I would have expected some inflation of memory as we'd be loading a `byte[]` with the file (so that'll be a little bit bigger than file in question) then doing an array copy into an immutable String object. So there is an increase but I wouldn't expect a ~80 times increase.

**Comment by andrewyatz** [comment]
Concerns raised over available stack memory. Retain original version. Recommend to add `throws IOException` to the method signature

**Comment by rkaushik15** [comment]
Made the changes adding 'throws' to the method signature instead of swallowing Exceptions. 
Also, a nice [blog post](https://www.novixys.com/blog/java-reading-large-file-efficiently/#6_With_Java_8_Streams) dealing with the reading file issue that we discussed, for an interesting read. :)

**Comment by andrewyatz** [comment]
Excellent thank you :)

**Comment by rkaushik15** [comment]
closing issue
