### ISSUE TITLE
Sequence is formatted as FASTA but refget returns a single line string

### ISSUE THREAD

**Issue by andrewyatz** [rkaushik15/api-compliance-framework#8]
There is currently a mismatch between what refget returns and what the test is slurping in. Meaning the tests for sequence content will never execute correctly. Consider switching this to either a single line in your source sequence or parse the FASTA sequence in Java.

**Comment by rkaushik15** [comment]
Made some changes to parse FASTA files in [this commit](https://github.com/rkaushik15/api-compliance-framework/commit/a415104f95a7eac0e49d43490c7002e2e2e207d3). Need to test the working against a refget server.

**Comment by andrewyatz** [comment]
I would test against http://refget.herokuapp.com/ until we can create a mock server for you. As for the parsing code [FASTA formatted header lines](https://en.wikipedia.org/wiki/FASTA_format) always start with `>`. So if you do a regex looking to remove a line that starts with `>` you'll always remove the correct line.

**Comment by rkaushik15** [comment]
After testing with refget servers, changes in https://github.com/rkaushik15/api-compliance-framework/commit/a415104f95a7eac0e49d43490c7002e2e2e207d3 seem to take care of this. Closing issue.
